export const SEND_NEW_MOVIE_DATA = 'SEND_NEW_MOVIE_DATA';
export const SEND_NEW_MOVIE_DATA_REQUEST = 'SEND_NEW_MOVIE_DATA_REQUEST';
export const SEND_NEW_MOVIE_DATA_SUCCESS = 'SEND_NEW_MOVIE_DATA_SUCCESS';
export const SEND_NEW_MOVIE_DATA_ERROR = 'SEND_NEW_MOVIE_DATA_ERROR';

export const GET_MOVIE_DATA_SUCCESS = 'GET_MOVIE_DATA_SUCCESS';

export const DELETE_MOVIE_DATA = 'DELETE_MOVIE_DATA';
export const DELETE_MOVIE_DATA_REQUEST = 'DELETE_MOVIE_DATA_REQUEST';
export const DELETE_MOVIE_DATA_SUCCESS = 'DELETE_MOVIE_DATA_SUCCESS';
export const DELETE_MOVIE_DATA_ERROR = 'DELETE_MOVIE_DATA_ERROR';

export const UPDATE_MOVIE_DATA = 'UPDATE_MOVIE_DATA';
export const UPDATE_MOVIE_DATA_REQUEST = 'UPDATE_MOVIE_DATA_REQUEST';
export const UPDATE_MOVIE_DATA_SUCCESS = 'UPDATE_MOVIE_DATA_SUCCESS';
export const UPDATE_MOVIE_DATA_ERROR = 'UPDATE_MOVIE_DATA_ERROR';