export const SEND_NEW_MOVIE_DATA_START = 'SEND_NEW_MOVIE_DATA_START';
export const SEND_NEW_MOVIE_DATA_SUCCESS = 'SEND_NEW_MOVIE_DATA_SUCCESS';
export const SEND_NEW_MOVIE_DATA_ERROR = 'SEND_NEW_MOVIE_DATA_ERROR';

export const GET_MOVIE_DATA_SUCCESS = 'GET_MOVIE_DATA_SUCCESS';