export const SEND_NEW_MOVIE_DATA = 'SEND_NEW_MOVIE_DATA';
export const SEND_NEW_MOVIE_DATA_REQUEST = 'SEND_NEW_MOVIE_DATA_REQUEST';
export const SEND_NEW_MOVIE_DATA_SUCCESS = 'SEND_NEW_MOVIE_DATA_SUCCESS';
export const SEND_NEW_MOVIE_DATA_ERROR = 'SEND_NEW_MOVIE_DATA_ERROR';

export const GET_MOVIE_DATA_SUCCESS = 'GET_MOVIE_DATA_SUCCESS';